# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 069e72916e5d31542557e6b4f3b0dd146a4f06b9472f90ccfcb794ca6c8dfa5f7577189016ab2d11d7b726686fb138930d3d3cf765b9bf126e3fa67178daa4d3

test:
  secret_key_base: f2ca6e45e45f773eded2aba85613edd226af3ab8b861be8886275371f660366204bab2c6905e55c05718d3d58f532bcb203bedc937f687621d962abba01fe820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
